Output hanoi.gif

Set Width 1400
Set Height 780
Set TypingSpeed 500ms
Set PlaybackSpeed 5

Type "hanoi" Sleep 2s  Enter 
Sleep 2s
Type "5" Sleep 3s  Enter
Sleep 2s
Type "1" Sleep 2s Type "3" Sleep 2s
Type "1" Sleep 2s Type "2" Sleep 2s
Type "3" Sleep 2s Type "2" Sleep 2s
Type "1" Sleep 2s Type "3" Sleep 2s
Type "2" Sleep 2s Type "1" Sleep 2s
Type "2" Sleep 2s Type "3" Sleep 2s
Type "1" Sleep 2s Type "3" Sleep 2s
Sleep 5s
